CREATE TABLE product
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255),
    type_product VARCHAR(255),
    price        BIGINT,
    barcode      VARCHAR(255) UNIQUE,
    created_at   DATE,
    updated_at   DATE
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(255),
    password     VARCHAR(255),
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    created_at   DATE,
    updated_at   DATE
);
