CREATE TABLE product
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255),
    type_product VARCHAR(255),
    price        BIGINT,
    barcode      VARCHAR(255) UNIQUE,
    created_at   DATE,
    updated_at   DATE
);
