server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: smartiot
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      schema: public
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        ddl-auto: validate
  flyway:
    user: postgres
    password: smartiot
    url: jdbc:postgresql://localhost:5432/postgres
    schemas: public

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base_path:
      path_mapping:
        prometheus: metrics

iot:
  api:
    prefix: "/iot"
  qr:
    width: 350
    height: 350
  security:
    secret: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9"
