server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: iot
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

iot:
  api:
    prefix: "/iot"
  qr:
    width: 350
    height: 350
