server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: iot
      password: smartiot
      username: smartiot
  datasource:
    username: postgres
    password: smartiot
    url: jdbc:postgresql://localhost:5432/postgres
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base_path:
      path_mapping:
        prometheus: metrics

iot:
  api:
    prefix: "/iot"
  qr:
    width: 350
    height: 350
  security:
    secret: "secret"
