CREATE TABLE products
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    type_product VARCHAR(255),
    price        BIGINT,
    barcode      VARCHAR(255) UNIQUE,
    created_at   DATE,
    updated_at   DATE
);

CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(255) UNIQUE NOT NULL,
    password     VARCHAR(255)        NOT NULL,
    email        VARCHAR(255)        NOT NULL UNIQUE,
    phone_number VARCHAR(255)        NOT NULL UNIQUE,
    created_at   DATE,
    updated_at   DATE
);

CREATE TABLE product_items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    type_product VARCHAR(255),
    count        BIGINT,
    price        BIGINT,
    barcode      VARCHAR(255),
    expired_date DATE,
    fridge_id    BIGINT,
    created_at   DATE,
    updated_at   DATE
);

CREATE TABLE fridges
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    qr_link    BYTEA        NOT NULL UNIQUE,
    created_at DATE,
    updated_at DATE
);

CREATE TABLE user_fridge
(
    user_id   BIGINT,
    fridge_id BIGINT
);
