version: '3.7'

services:
  postres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: smartiot
    networks:
      - iot-network
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: smartiot
      MONGO_INITDB_ROOT_PASSWORD: smartiot
    networks:
      - iot-network
  service-iot:
    image: iot-service:latest
    hostname: oracle-db-ils
    ports:
      - "8080:8080"
    volumes:
      - iot-data:/opt/iot-data
    networks:
      - iot-network

networks:
  iot-network:
    name: iot-network
